FROM node:22-alpine.19 AS build
WORKDIR /app
COPY . .
RUN npm i
RUN npm i -g @angular/cli
RUN ng build -c production

FROM node:22-alpine.19 AS run
WORKDIR /app
COPY --from-build app/dist/e-shop.web/browser /app
RUN npm install -g http-server

EXPOSE 8080
CMD ["http-server", "", "8080"]